### ISSUE TITLE
Error while executing dev setup script.

### ISSUE THREAD

**Issue by anilbhanushali** [nilenso/time-tracker#151]
`ERROR time-tracker.migration: {"event":"time-tracker.migration/migration-failed"}
org.postgresql.util.PSQLException: This ResultSet is closed.
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2852)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1875)
	at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:37)
	at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:221)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1853)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:382)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:904)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:619)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:611)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:598)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:811)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:806)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:843)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:823)
	at clojure.java.jdbc$execute_BANG_$execute_helper__765.invoke(jdbc.clj:1008)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1012)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:989)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1000)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:989)
	at ragtime.jdbc$ensure_migrations_table_exists.invokeStatic(jdbc.clj:36)
	at ragtime.jdbc$ensure_migrations_table_exists.invoke(jdbc.clj:34)
	at ragtime.jdbc.SqlDatabase.applied_migration_ids(jdbc.clj:55)
	at ragtime.core$migrate_all.invokeStatic(core.clj:43)
	at ragtime.core$migrate_all.invoke(core.clj:32)
	at ragtime.repl$migrate.invokeStatic(repl.clj:49)
	at ragtime.repl$migrate.invoke(repl.clj:34)
	at time_tracker.migration$migrate_db$fn__3277.invoke(migration.clj:16)
	at time_tracker.migration$migrate_db.invokeStatic(migration.clj:15)
	at time_tracker.migration$migrate_db.invoke(migration.clj:13)
	at time_tracker.migration$lein_migrate_db.invokeStatic(migration.clj:35)
	at time_tracker.migration$lein_migrate_db.invoke(migration.clj:33)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval15.invokeStatic(form-init288285839060514281.clj:1)
	at user$eval15.invoke(form-init288285839060514281.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6977)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7429)
	at clojure.lang.Compiler.loadFile(Compiler.java:7367)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)`

**Comment by kirang89** [comment]
@anilbhanushali I just tried setting up the project from scratch and it worked. Could you post the complete shell output when running `dev-setup.sh`?

**Comment by anilbhanushali** [comment]
@kirang89 please find the log attached.
<img width="619" alt="screenshot 2018-02-27 14 04 27" src="https://user-images.githubusercontent.com/7549804/36718312-508f8f0a-1bc7-11e8-912a-15fac93be70c.png">
[time-tracker.log](https://github.com/nilenso/time-tracker/files/1761805/time-tracker.log)

**Comment by kirang89** [comment]
Does `:db-connection-string` in `profiles.clj` reflect your actual database uri?

**Comment by anilbhanushali** [comment]
Yes, also i can see the database 'time_tracker' and 'time_tracker_test' created but no tables.

**Comment by kirang89** [comment]
What version of postgres are you using?

**Comment by kirang89** [comment]
@anilbhanushali Tried running the setup script on my colleague's machine running Postgres 10 and it failed with the same error that you encountered. [This commit](https://github.com/nilenso/time-tracker/commit/a7febccafaf4f75a852eac605f5d7e3013541741) fixes that issue. Could you try again and let me know?

**Comment by anilbhanushali** [comment]
This worked.

**Comment by kirang89** [comment]
Awesome, thanks! :)
